version: '2'

services:
  app:
    image: golang:1.10-alpine3.7
    container_name: go
    volumes:
      - "./src:/go/src/"
    ports:
      - "80:8080"
    working_dir: /go/src/${PROJECT_NAME}/
    command: go run main.go
