FROM golang:alpine AS builder

WORKDIR $GOPATH/src/soma/
COPY ./src/. .

RUN GOOS=linux go build -ldflags="-w -s" -o /go/bin/soma

FROM scratch

COPY --from=builder /go/bin/soma /go/bin/soma

ENTRYPOINT ["/go/bin/soma"]

